#!/usr/bin/python
# -*- coding: utf-8 -*-
import numpy as np
import matplotlib.pyplot as plt

x=[1,1,2]

y=[3,5,4]

fig, ax = plt.subplots()
line1, = ax.plot(x, y,'*')


ax.legend(loc='lower right')
plt.show()

